name: Prod Deployment
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_HOST_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Set up Docker context for prod
        run: |
          docker context create prod-server \
            --docker "host=ssh://${{ secrets.SERVER_HOST_USER }}@${{ secrets.SERVER_HOST_IP }}" \
            --description "Prod server context"
          docker context use prod-server

      - name: Deploy to Remote Prod Server
        run: |
          echo "Deploying to Prod Server..."

          docker compose -f docker-compose.prod.yml up -d --build --no-deps --force-recreate

        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          BOT_ENVIRONMENT: ${{ secrets.BOT_ENVIRONMENT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_FEEDBACK_URL: ${{ secrets.SENTRY_FEEDBACK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_DEFAULT_USER }}
          RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_DEFAULT_PASS }}
          RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
